apiVersion: v1
kind: Secret
metadata:
  name: changeguard-backup-secrets
  namespace: dbguard
type: Opaque
stringData:
  CHANGEGUARD_BACKUP_DSN: postgres://backup_user:replace-me@postgres.example:5432/dbguard?sslmode=require
